// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPaTMspuWoLlfmlxumUPzFRavjQVsC7j8',
    appId: '1:528224603938:web:57602e6b108de943c15f7b',
    messagingSenderId: '528224603938',
    projectId: 'music-vibe-718b5',
    authDomain: 'music-vibe-718b5.firebaseapp.com',
    storageBucket: 'music-vibe-718b5.firebasestorage.app',
    measurementId: 'G-SMRTRC64VG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAD2FDoN3Pswt-ES_tupABdZl_6Mg680Xs',
    appId: '1:528224603938:android:b856163fe80a9076c15f7b',
    messagingSenderId: '528224603938',
    projectId: 'music-vibe-718b5',
    storageBucket: 'music-vibe-718b5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8sNllmfWoDYnpEP87P0N3rjbo_ZR2uTI',
    appId: '1:528224603938:ios:21a16db68979530cc15f7b',
    messagingSenderId: '528224603938',
    projectId: 'music-vibe-718b5',
    storageBucket: 'music-vibe-718b5.firebasestorage.app',
    iosBundleId: 'com.example.mpx',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8sNllmfWoDYnpEP87P0N3rjbo_ZR2uTI',
    appId: '1:528224603938:ios:21a16db68979530cc15f7b',
    messagingSenderId: '528224603938',
    projectId: 'music-vibe-718b5',
    storageBucket: 'music-vibe-718b5.firebasestorage.app',
    iosBundleId: 'com.example.mpx',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCPaTMspuWoLlfmlxumUPzFRavjQVsC7j8',
    appId: '1:528224603938:web:5ecec9fc61df2ecac15f7b',
    messagingSenderId: '528224603938',
    projectId: 'music-vibe-718b5',
    authDomain: 'music-vibe-718b5.firebaseapp.com',
    storageBucket: 'music-vibe-718b5.firebasestorage.app',
    measurementId: 'G-0JWB1LFB16',
  );

}